typedef CategorySeed = ({
  String id,
  int kind,
  String name,
  String iconKey,
  int sortOrder,
  String? parentId,
  int level,
});

const defaultCategorySeeds = <CategorySeed>[
  (
    id: 'expense_food',
    kind: 0,
    name: '餐饮',
    iconKey: 'restaurant',
    sortOrder: 0,
    parentId: null,
    level: 1,
  ),
  (
    id: 'expense_food_meals',
    kind: 0,
    name: '三餐',
    iconKey: 'meal',
    sortOrder: 0,
    parentId: 'expense_food',
    level: 2,
  ),
  (
    id: 'expense_food_groceries',
    kind: 0,
    name: '买菜',
    iconKey: 'vegetable',
    sortOrder: 1,
    parentId: 'expense_food',
    level: 2,
  ),
  (
    id: 'expense_food_snacks',
    kind: 0,
    name: '零食',
    iconKey: 'snack',
    sortOrder: 2,
    parentId: 'expense_food',
    level: 2,
  ),
  (
    id: 'expense_food_drinks',
    kind: 0,
    name: '饮料',
    iconKey: 'drink',
    sortOrder: 3,
    parentId: 'expense_food',
    level: 2,
  ),
  (
    id: 'expense_transport',
    kind: 0,
    name: '交通',
    iconKey: 'transport',
    sortOrder: 1,
    parentId: null,
    level: 1,
  ),
  (
    id: 'expense_transport_public',
    kind: 0,
    name: '公交地铁',
    iconKey: 'subway',
    sortOrder: 0,
    parentId: 'expense_transport',
    level: 2,
  ),
  (
    id: 'expense_transport_taxi',
    kind: 0,
    name: '打车',
    iconKey: 'taxi',
    sortOrder: 1,
    parentId: 'expense_transport',
    level: 2,
  ),
  (
    id: 'expense_transport_bike',
    kind: 0,
    name: '骑行',
    iconKey: 'bike',
    sortOrder: 2,
    parentId: 'expense_transport',
    level: 2,
  ),
  (
    id: 'expense_transport_long',
    kind: 0,
    name: '长途交通',
    iconKey: 'train',
    sortOrder: 3,
    parentId: 'expense_transport',
    level: 2,
  ),
  (
    id: 'expense_shopping',
    kind: 0,
    name: '购物',
    iconKey: 'shopping',
    sortOrder: 2,
    parentId: null,
    level: 1,
  ),
  (
    id: 'expense_shopping_daily',
    kind: 0,
    name: '日用品',
    iconKey: 'shopping',
    sortOrder: 0,
    parentId: 'expense_shopping',
    level: 2,
  ),
  (
    id: 'expense_shopping_clothing',
    kind: 0,
    name: '服饰',
    iconKey: 'clothes',
    sortOrder: 1,
    parentId: 'expense_shopping',
    level: 2,
  ),
  (
    id: 'expense_shopping_digital',
    kind: 0,
    name: '数码',
    iconKey: 'digital',
    sortOrder: 2,
    parentId: 'expense_shopping',
    level: 2,
  ),
  (
    id: 'expense_shopping_home',
    kind: 0,
    name: '家居',
    iconKey: 'home',
    sortOrder: 3,
    parentId: 'expense_shopping',
    level: 2,
  ),
  (
    id: 'expense_housing',
    kind: 0,
    name: '居住',
    iconKey: 'home',
    sortOrder: 3,
    parentId: null,
    level: 1,
  ),
  (
    id: 'expense_housing_rent',
    kind: 0,
    name: '房租',
    iconKey: 'rent',
    sortOrder: 0,
    parentId: 'expense_housing',
    level: 2,
  ),
  (
    id: 'expense_housing_utilities',
    kind: 0,
    name: '水电燃气',
    iconKey: 'utilities',
    sortOrder: 1,
    parentId: 'expense_housing',
    level: 2,
  ),
  (
    id: 'expense_housing_property',
    kind: 0,
    name: '物业',
    iconKey: 'property',
    sortOrder: 2,
    parentId: 'expense_housing',
    level: 2,
  ),
  (
    id: 'expense_entertainment',
    kind: 0,
    name: '娱乐',
    iconKey: 'fun',
    sortOrder: 4,
    parentId: null,
    level: 1,
  ),
  (
    id: 'expense_entertainment_media',
    kind: 0,
    name: '影音',
    iconKey: 'movie',
    sortOrder: 0,
    parentId: 'expense_entertainment',
    level: 2,
  ),
  (
    id: 'expense_entertainment_games',
    kind: 0,
    name: '游戏',
    iconKey: 'game',
    sortOrder: 1,
    parentId: 'expense_entertainment',
    level: 2,
  ),
  (
    id: 'expense_entertainment_travel',
    kind: 0,
    name: '旅行',
    iconKey: 'travel',
    sortOrder: 2,
    parentId: 'expense_entertainment',
    level: 2,
  ),
  (
    id: 'expense_entertainment_sports',
    kind: 0,
    name: '运动',
    iconKey: 'sport',
    sortOrder: 3,
    parentId: 'expense_entertainment',
    level: 2,
  ),
  (
    id: 'expense_medical',
    kind: 0,
    name: '医疗',
    iconKey: 'medical',
    sortOrder: 5,
    parentId: null,
    level: 1,
  ),
  (
    id: 'expense_medical_medicine',
    kind: 0,
    name: '药品',
    iconKey: 'medicine',
    sortOrder: 0,
    parentId: 'expense_medical',
    level: 2,
  ),
  (
    id: 'expense_medical_clinic',
    kind: 0,
    name: '门诊',
    iconKey: 'clinic',
    sortOrder: 1,
    parentId: 'expense_medical',
    level: 2,
  ),
  (
    id: 'expense_family',
    kind: 0,
    name: '亲友',
    iconKey: 'family',
    sortOrder: 6,
    parentId: null,
    level: 1,
  ),
  (
    id: 'expense_family_daily',
    kind: 0,
    name: '家人',
    iconKey: 'family',
    sortOrder: 0,
    parentId: 'expense_family',
    level: 2,
  ),
  (
    id: 'expense_family_gifts',
    kind: 0,
    name: '红包礼物',
    iconKey: 'gift',
    sortOrder: 1,
    parentId: 'expense_family',
    level: 2,
  ),
  (
    id: 'expense_pet',
    kind: 0,
    name: '宠物',
    iconKey: 'pet',
    sortOrder: 7,
    parentId: null,
    level: 1,
  ),
  (
    id: 'expense_pet_food',
    kind: 0,
    name: '宠物食品',
    iconKey: 'pet_food',
    sortOrder: 0,
    parentId: 'expense_pet',
    level: 2,
  ),
  (
    id: 'expense_pet_medical',
    kind: 0,
    name: '宠物医疗',
    iconKey: 'medical',
    sortOrder: 1,
    parentId: 'expense_pet',
    level: 2,
  ),
  (
    id: 'expense_pet_supplies',
    kind: 0,
    name: '宠物用品',
    iconKey: 'pet',
    sortOrder: 2,
    parentId: 'expense_pet',
    level: 2,
  ),
  (
    id: 'expense_education',
    kind: 0,
    name: '学习',
    iconKey: 'study',
    sortOrder: 8,
    parentId: null,
    level: 1,
  ),
  (
    id: 'expense_education_courses',
    kind: 0,
    name: '课程',
    iconKey: 'course',
    sortOrder: 0,
    parentId: 'expense_education',
    level: 2,
  ),
  (
    id: 'expense_education_books',
    kind: 0,
    name: '书籍',
    iconKey: 'book',
    sortOrder: 1,
    parentId: 'expense_education',
    level: 2,
  ),
  (
    id: 'expense_other',
    kind: 0,
    name: '其他',
    iconKey: 'other',
    sortOrder: 9,
    parentId: null,
    level: 1,
  ),
  (
    id: 'income_salary',
    kind: 1,
    name: '工资',
    iconKey: 'salary',
    sortOrder: 0,
    parentId: null,
    level: 1,
  ),
  (
    id: 'income_bonus',
    kind: 1,
    name: '奖金',
    iconKey: 'bonus',
    sortOrder: 1,
    parentId: null,
    level: 1,
  ),
  (
    id: 'income_part_time',
    kind: 1,
    name: '兼职',
    iconKey: 'part_time',
    sortOrder: 2,
    parentId: null,
    level: 1,
  ),
  (
    id: 'income_finance',
    kind: 1,
    name: '理财',
    iconKey: 'finance',
    sortOrder: 3,
    parentId: null,
    level: 1,
  ),
  (
    id: 'income_gift',
    kind: 1,
    name: '红包礼金',
    iconKey: 'red_packet',
    sortOrder: 4,
    parentId: null,
    level: 1,
  ),
  (
    id: 'income_other',
    kind: 1,
    name: '其他',
    iconKey: 'other',
    sortOrder: 5,
    parentId: null,
    level: 1,
  ),
];

// Migrate unpublished development builds without keeping personal data as
// product defaults.
const deprecatedCategoryMapping = <String, String>{
  '41046968': 'expense_food',
  '41010717': 'expense_entertainment_travel',
  '41010725': 'expense_shopping',
  '41010726': 'expense_medical',
  '41010727': 'expense_family_gifts',
  '41010729': 'expense_entertainment',
  '41010730': 'expense_family_gifts',
  '41049266': 'expense_shopping_daily',
  '41010732': 'expense_entertainment_sports',
  '41046595': 'expense_other',
  '41010733': 'expense_other',
  '41010731': 'expense_shopping_digital',
  '41010716': 'expense_transport',
  '41010720': 'expense_housing_utilities',
  '41010722': 'expense_education',
  '41048025': 'expense_other',
  '41010723': 'expense_shopping_daily',
  '41010715': 'expense_shopping_clothing',
  '55988758': 'expense_family_daily',
  '57401145': 'expense_other',
  '59073155': 'expense_family_daily',
  '77650933': 'expense_housing_utilities',
  '79962220': 'expense_housing_rent',
  '84566799': 'expense_family_daily',
  '121279878': 'expense_family_gifts',
  '123685167': 'expense_pet',
  '95913605': 'expense_food_meals',
  '95913749': 'expense_food_groceries',
  '95913354': 'expense_food_meals',
  '95913315': 'expense_food_drinks',
  '106948994': 'expense_food_drinks',
  '95913284': 'expense_food_groceries',
  '95913353': 'expense_food_snacks',
  '95914786': 'expense_transport_public',
  '95914788': 'expense_transport_public',
  '95914793': 'expense_transport_taxi',
  '95914824': 'expense_transport_bike',
  '95914827': 'expense_transport_long',
  '95914831': 'expense_transport_long',
  '107150874': 'expense_transport',
  '65873378': 'expense_entertainment_games',
  '95912863': 'expense_entertainment_media',
  '126119580': 'expense_entertainment_games',
  '136714938': 'expense_entertainment_games',
  '78717798': 'expense_housing_utilities',
  '78717799': 'expense_housing_property',
  '78717801': 'expense_housing_utilities',
  '124968315': 'expense_housing_utilities',
  '134016139': 'expense_housing_utilities',
  '123685199': 'expense_pet',
  '135384756': 'expense_pet',
  '107357683': 'expense_pet',
  '41010735': 'income_salary',
  '41010736': 'income_other',
  '41010737': 'income_gift',
  '41010738': 'income_part_time',
  '41010739': 'income_finance',
  '41010740': 'income_other',
  '41048146': 'income_other',
  '51838995': 'income_other',
  '113666733': 'income_bonus',
};

const legacyCategoryMapping = <String, String>{
  'expense_food': 'expense_food_meals',
  'expense_transport': 'expense_transport',
  'expense_shopping': 'expense_shopping',
  'expense_home': 'expense_housing',
  'expense_fun': 'expense_entertainment',
  'expense_medical': 'expense_medical',
  'expense_pet': 'expense_pet',
  'expense_other': 'expense_other',
  'income_salary': 'income_salary',
  'income_bonus': 'income_bonus',
  'income_part_time': 'income_part_time',
  'income_finance': 'income_finance',
  'income_other': 'income_other',
};
